# Generated by Django 5.1.4 on 2025-01-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0002_message_read_alter_message_date_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
