# Generated by Django 5.1.4 on 2025-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0003_alter_frequency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
