# Generated by Django 5.1.4 on 2025-01-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0003_alter_class_id_alter_class_supervising_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_school', to='SchoolDiaryApp.school'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
