# Generated by Django 5.1.4 on 2025-01-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0004_student_school_alter_customuser_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
        migrations.AlterField(
            model_name='director',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directors_school', to='SchoolDiaryApp.school'),
        ),
    ]
