# Generated by Django 5.1.4 on 2025-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0005_alter_announcements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Nauczyciel'), ('Director', 'Dyrektor'), ('Parent', 'Rodzic'), ('Administrator', 'Administrator')], default='student', max_length=15),
        ),
    ]
