# Generated by Django 5.1.4 on 2025-01-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0005_remove_subject_subject_id_alter_director_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_school', to='SchoolDiaryApp.school'),
        ),
    ]
