# Generated by Django 5.1.4 on 2025-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0006_subject_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
    ]
