# Generated by Django 5.1.4 on 2025-01-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers_school', to='SchoolDiaryApp.school'),
        ),
    ]
