# Generated by Django 5.1.4 on 2025-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0007_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grate',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
