# Generated by Django 5.1.4 on 2025-01-19 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDiaryApp', '0008_alter_grate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='SchoolDiaryApp.student'),
        ),
    ]
